using Surf2.Models;
using static Surf2.Storage.Relational.State.StateField;

namespace Surf2.Storage.Relational.State;

internal static class StateMaps
{
    public static readonly StateRowMap<Scope> Scope = new("Scope", "ScopeKey",
        Text<Scope>(nameof(Models.Scope.ScopeId), v => v.ScopeId, (v,x) => v.ScopeId=x),
        Text<Scope>(nameof(Models.Scope.Name), v => v.Name, (v,x) => v.Name=x),
        Text<Scope>(nameof(Models.Scope.Description), v => v.Description, (v,x) => v.Description=x, true));
    public static readonly StateRowMap<ScopedResource> Resource = new("ScopeResource", "ScopeResourceKey",
        Text<ScopedResource>(nameof(ScopedResource.ResourceId), v => v.ResourceId, (v,x) => v.ResourceId=x),
        Enum<ScopedResource, ResourceKind>(nameof(ScopedResource.Kind), v => v.Kind, (v,x) => v.Kind=x),
        Text<ScopedResource>(nameof(ScopedResource.Path), v => v.Path, (v,x) => v.Path=x),
        Text<ScopedResource>(nameof(ScopedResource.DisplayNameOverride), v => v.DisplayNameOverride, (v,x) => v.DisplayNameOverride=x),
        Text<ScopedResource>(nameof(ScopedResource.DetailsOverride), v => v.DetailsOverride, (v,x) => v.DetailsOverride=x, true),
        Time<ScopedResource>(nameof(ScopedResource.AddedAtUtc), v => v.AddedAtUtc, (v,x) => v.AddedAtUtc=x),
        Bool<ScopedResource>(nameof(ScopedResource.IncludeChildren), v => v.IncludeChildren, (v,x) => v.IncludeChildren=x));
    public static readonly StateRowMap<VirtualFolder> Folder = new("VirtualFolder", "VirtualFolderKey",
        Text<VirtualFolder>(nameof(VirtualFolder.VirtualFolderId), v => v.VirtualFolderId, (v,x) => v.VirtualFolderId=x),
        Text<VirtualFolder>(nameof(VirtualFolder.Name), v => v.Name, (v,x) => v.Name=x),
        Text<VirtualFolder>(nameof(VirtualFolder.ParentNodeKey), v => v.ParentNodeKey, (v,x) => v.ParentNodeKey=x));
    public static readonly StateRowMap<DiagramDocument> Diagram = new("DiagramRevision", "DiagramRevisionKey",
        Text<DiagramDocument>(nameof(DiagramDocument.DiagramId), v => v.DiagramId, (v,x) => v.DiagramId=x),
        Text<DiagramDocument>(nameof(DiagramDocument.Name), v => v.Name, (v,x) => v.Name=x),
        Time<DiagramDocument>(nameof(DiagramDocument.CreatedAtUtc), v => v.CreatedAtUtc, (v,x) => v.CreatedAtUtc=x),
        Time<DiagramDocument>(nameof(DiagramDocument.UpdatedAtUtc), v => v.UpdatedAtUtc, (v,x) => v.UpdatedAtUtc=x),
        Float<DiagramDocument>(nameof(DiagramDocument.CanvasZoom), v => v.CanvasZoom, (v,x) => v.CanvasZoom=x),
        Float<DiagramDocument>(nameof(DiagramDocument.ViewportHorizontalOffset), v => v.ViewportHorizontalOffset, (v,x) => v.ViewportHorizontalOffset=x),
        Float<DiagramDocument>(nameof(DiagramDocument.ViewportVerticalOffset), v => v.ViewportVerticalOffset, (v,x) => v.ViewportVerticalOffset=x));
    public static readonly StateRowMap<DiagramObjectSnapshot> Object = new("DiagramObject", "DiagramObjectKey",
        Text<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.Id), v => v.Id, (v,x) => v.Id=x),
        Enum<DiagramObjectSnapshot, DiagramObjectType>(nameof(DiagramObjectSnapshot.ObjectType), v => v.ObjectType, (v,x) => v.ObjectType=x),
        Int<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.ZIndex), v => v.ZIndex, (v,x) => v.ZIndex=x),
        Text<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.WorkflowId), v => v.WorkflowId, (v,x) => v.WorkflowId=x),
        Text<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.WorkflowItemId), v => v.WorkflowItemId, (v,x) => v.WorkflowItemId=x),
        Text<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.PortalName), v => v.PortalName, (v,x) => v.PortalName=x),
        Text<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.PairedPortalDiagramId), v => v.PairedPortalDiagramId, (v,x) => v.PairedPortalDiagramId=x),
        Text<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.PairedPortalObjectId), v => v.PairedPortalObjectId, (v,x) => v.PairedPortalObjectId=x),
        Enum<DiagramObjectSnapshot, DiagramShapeKind>(nameof(DiagramObjectSnapshot.ShapeKind), v => v.ShapeKind, (v,x) => v.ShapeKind=x),
        Text<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.ImageDefinitionId), v => v.ImageDefinitionId, (v,x) => v.ImageDefinitionId=x),
        Text<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.ImageName), v => v.ImageName, (v,x) => v.ImageName=x),
        Text<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.ImageDataBase64), v => v.ImageDataBase64, (v,x) => v.ImageDataBase64=x, true),
        Text<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.PastedImageFileName), v => v.PastedImageFileName, (v,x) => v.PastedImageFileName=x),
        Text<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.LabelText), v => v.LabelText, (v,x) => v.LabelText=x, true),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.LabelFontSize), v => v.LabelFontSize, (v,x) => v.LabelFontSize=x),
        Text<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.OutlineColorText), v => v.OutlineColorText, (v,x) => v.OutlineColorText=x),
        Text<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.BackColorText), v => v.BackColorText, (v,x) => v.BackColorText=x),
        Bool<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.HasEndArrow), v => v.HasEndArrow, (v,x) => v.HasEndArrow=x),
        Bool<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.IsLineLoose), v => v.IsLineLoose, (v,x) => v.IsLineLoose=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.LineStartX), v => v.LineStartX, (v,x) => v.LineStartX=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.LineStartY), v => v.LineStartY, (v,x) => v.LineStartY=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.LineEndX), v => v.LineEndX, (v,x) => v.LineEndX=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.LineEndY), v => v.LineEndY, (v,x) => v.LineEndY=x),
        Bool<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.IsTethered), v => v.IsTethered, (v,x) => v.IsTethered=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.LabelAnchorX), v => v.LabelAnchorX, (v,x) => v.LabelAnchorX=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.LabelAnchorY), v => v.LabelAnchorY, (v,x) => v.LabelAnchorY=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.LabelBoxLeft), v => v.LabelBoxLeft, (v,x) => v.LabelBoxLeft=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.LabelBoxTop), v => v.LabelBoxTop, (v,x) => v.LabelBoxTop=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.LabelBoxWidth), v => v.LabelBoxWidth, (v,x) => v.LabelBoxWidth=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.LabelBoxHeight), v => v.LabelBoxHeight, (v,x) => v.LabelBoxHeight=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.Left), v => v.Left, (v,x) => v.Left=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.Top), v => v.Top, (v,x) => v.Top=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.Width), v => v.Width, (v,x) => v.Width=x),
        Float<DiagramObjectSnapshot>(nameof(DiagramObjectSnapshot.Height), v => v.Height, (v,x) => v.Height=x),
        Text<DiagramObjectSnapshot>("Metadata.Link", v => v.Metadata.Link, (v,x) => v.Metadata.Link=x, column: "MetadataLink"),
        Text<DiagramObjectSnapshot>("Metadata.DocumentationXaml", v => v.Metadata.DocumentationXaml,
            (v,x) => v.Metadata.DocumentationXaml=x, true, "DocumentationXamlContentKey"));
    public static readonly StateRowMap<WorkflowDocument> Workflow = new("Workflow", "WorkflowKey",
        Text<WorkflowDocument>(nameof(WorkflowDocument.WorkflowId), v => v.WorkflowId, (v,x) => v.WorkflowId=x),
        Text<WorkflowDocument>(nameof(WorkflowDocument.WorkflowName), v => v.WorkflowName, (v,x) => v.WorkflowName=x),
        Time<WorkflowDocument>(nameof(WorkflowDocument.CreatedAtUtc), v => v.CreatedAtUtc, (v,x) => v.CreatedAtUtc=x),
        Time<WorkflowDocument>(nameof(WorkflowDocument.UpdatedAtUtc), v => v.UpdatedAtUtc, (v,x) => v.UpdatedAtUtc=x),
        Bool<WorkflowDocument>(nameof(WorkflowDocument.AreMarkersVisible), v => v.AreMarkersVisible, (v,x) => v.AreMarkersVisible=x));
    public static readonly StateRowMap<WorkflowItem> Item = new("WorkflowItem", "WorkflowItemKey",
        Text<WorkflowItem>(nameof(WorkflowItem.WorkflowItemId), v => v.WorkflowItemId, (v,x) => v.WorkflowItemId=x),
        Text<WorkflowItem>(nameof(WorkflowItem.MarkerDiagramObjectId), v => v.MarkerDiagramObjectId, (v,x) => v.MarkerDiagramObjectId=x),
        Int<WorkflowItem>(nameof(WorkflowItem.ItemNumber), v => v.ItemNumber, (v,x) => v.ItemNumber=x),
        Text<WorkflowItem>(nameof(WorkflowItem.ItemDescription), v => v.ItemDescription, (v,x) => v.ItemDescription=x, true),
        Text<WorkflowItem>(nameof(WorkflowItem.ItemDocumentationXaml), v => v.ItemDocumentationXaml, (v,x) => v.ItemDocumentationXaml=x, true));
    public static readonly StateRowMap<QueryItem> Query = new("QueryItem", "QueryItemKey",
        Text<QueryItem>(nameof(QueryItem.QueryId), v => v.QueryId, (v,x) => v.QueryId=x),
        Int<QueryItem>(nameof(QueryItem.QueryNumber), v => v.QueryNumber, (v,x) => v.QueryNumber=x),
        Time<QueryItem>(nameof(QueryItem.CreatedDateUtc), v => v.CreatedDateUtc, (v,x) => v.CreatedDateUtc=x),
        Enum<QueryItem, QueryStatus>(nameof(QueryItem.Status), v => v.Status, (v,x) => v.Status=x),
        Text<QueryItem>(nameof(QueryItem.QueryDescription), v => v.QueryDescription, (v,x) => v.QueryDescription=x, true));
    public static readonly StateRowMap<OpenDocumentState> Window = new("DocumentWindowState", "DocumentWindowKey",
        NullableKey<OpenDocumentState>(nameof(OpenDocumentState.BoundSnapshotKey), v => v.BoundSnapshotKey, (v,x) => v.BoundSnapshotKey=x),
        NullableKey<OpenDocumentState>(nameof(OpenDocumentState.BoundResourceKey), v => v.BoundResourceKey, (v,x) => v.BoundResourceKey=x),
        Enum<OpenDocumentState, SavedDocumentTargetState>(nameof(OpenDocumentState.TargetState), v => v.TargetState, (v,x) => v.TargetState=x),
        Text<OpenDocumentState>(nameof(OpenDocumentState.FilePath), v => v.FilePath, (v,x) => v.FilePath=x),
        Text<OpenDocumentState>(nameof(OpenDocumentState.DisplayName), v => v.DisplayName, (v,x) => v.DisplayName=x),
        Float<OpenDocumentState>(nameof(OpenDocumentState.Left), v => v.Left, (v,x) => v.Left=x),
        Float<OpenDocumentState>(nameof(OpenDocumentState.Top), v => v.Top, (v,x) => v.Top=x),
        Float<OpenDocumentState>(nameof(OpenDocumentState.Width), v => v.Width, (v,x) => v.Width=x),
        Float<OpenDocumentState>(nameof(OpenDocumentState.Height), v => v.Height, (v,x) => v.Height=x),
        Float<OpenDocumentState>(nameof(OpenDocumentState.FontSize), v => v.FontSize, (v,x) => v.FontSize=x),
        Float<OpenDocumentState>(nameof(OpenDocumentState.HorizontalOffset), v => v.HorizontalOffset, (v,x) => v.HorizontalOffset=x),
        Float<OpenDocumentState>(nameof(OpenDocumentState.VerticalOffset), v => v.VerticalOffset, (v,x) => v.VerticalOffset=x));
    public static readonly StateRowMap<WorkspaceState> Workspace = new("WorkspaceSession", "WorkspaceSessionKey",
        NullableText<WorkspaceState>(nameof(WorkspaceState.LastFolderPath), v => v.LastFolderPath, (v,x) => v.LastFolderPath=x),
        Float<WorkspaceState>(nameof(WorkspaceState.CanvasZoom), v => v.CanvasZoom, (v,x) => v.CanvasZoom=x),
        Float<WorkspaceState>(nameof(WorkspaceState.ViewportHorizontalOffset), v => v.ViewportHorizontalOffset, (v,x) => v.ViewportHorizontalOffset=x),
        Float<WorkspaceState>(nameof(WorkspaceState.ViewportVerticalOffset), v => v.ViewportVerticalOffset, (v,x) => v.ViewportVerticalOffset=x));
    public static readonly StateRowMap<ReferenceConnectionLineState> Connection = new("ReferenceConnectionLine", "ReferenceConnectionLineKey",
        NullableKey<ReferenceConnectionLineState>(nameof(ReferenceConnectionLineState.SourceBoundSnapshotKey), v => v.SourceBoundSnapshotKey, (v,x) => v.SourceBoundSnapshotKey=x),
        NullableKey<ReferenceConnectionLineState>(nameof(ReferenceConnectionLineState.SourceBoundResourceKey), v => v.SourceBoundResourceKey, (v,x) => v.SourceBoundResourceKey=x),
        Enum<ReferenceConnectionLineState, SavedDocumentTargetState>(nameof(ReferenceConnectionLineState.SourceTargetState), v => v.SourceTargetState, (v,x) => v.SourceTargetState=x),
        NullableKey<ReferenceConnectionLineState>(nameof(ReferenceConnectionLineState.TargetBoundSnapshotKey), v => v.TargetBoundSnapshotKey, (v,x) => v.TargetBoundSnapshotKey=x),
        NullableKey<ReferenceConnectionLineState>(nameof(ReferenceConnectionLineState.TargetBoundResourceKey), v => v.TargetBoundResourceKey, (v,x) => v.TargetBoundResourceKey=x),
        Enum<ReferenceConnectionLineState, SavedDocumentTargetState>(nameof(ReferenceConnectionLineState.TargetTargetState), v => v.TargetTargetState, (v,x) => v.TargetTargetState=x),
        Text<ReferenceConnectionLineState>(nameof(ReferenceConnectionLineState.ConnectionId), v => v.ConnectionId, (v,x) => v.ConnectionId=x),
        Text<ReferenceConnectionLineState>(nameof(ReferenceConnectionLineState.SourceFilePath), v => v.SourceFilePath, (v,x) => v.SourceFilePath=x),
        Int<ReferenceConnectionLineState>(nameof(ReferenceConnectionLineState.SourceLineNumber), v => v.SourceLineNumber, (v,x) => v.SourceLineNumber=x),
        Int<ReferenceConnectionLineState>(nameof(ReferenceConnectionLineState.SourceStartColumnNumber), v => v.SourceStartColumnNumber, (v,x) => v.SourceStartColumnNumber=x),
        Int<ReferenceConnectionLineState>(nameof(ReferenceConnectionLineState.SourceEndColumnNumber), v => v.SourceEndColumnNumber, (v,x) => v.SourceEndColumnNumber=x),
        Text<ReferenceConnectionLineState>(nameof(ReferenceConnectionLineState.TargetFilePath), v => v.TargetFilePath, (v,x) => v.TargetFilePath=x),
        Int<ReferenceConnectionLineState>(nameof(ReferenceConnectionLineState.TargetLineNumber), v => v.TargetLineNumber, (v,x) => v.TargetLineNumber=x),
        Int<ReferenceConnectionLineState>(nameof(ReferenceConnectionLineState.TargetStartColumnNumber), v => v.TargetStartColumnNumber, (v,x) => v.TargetStartColumnNumber=x),
        Int<ReferenceConnectionLineState>(nameof(ReferenceConnectionLineState.TargetEndColumnNumber), v => v.TargetEndColumnNumber, (v,x) => v.TargetEndColumnNumber=x));
    public static readonly StateRowMap<WorkbenchState> Workbench = new("Workbench", "WorkbenchKey",
        Text<WorkbenchState>(nameof(WorkbenchState.WorkbenchId), v => v.WorkbenchId, (v,x) => v.WorkbenchId=x),
        Text<WorkbenchState>(nameof(WorkbenchState.Name), v => v.Name, (v,x) => v.Name=x),
        Bool<WorkbenchState>(nameof(WorkbenchState.IsDefaultForScope), v => v.IsDefaultForScope, (v,x) => v.IsDefaultForScope=x),
        Time<WorkbenchState>(nameof(WorkbenchState.CreatedAtUtc), v => v.CreatedAtUtc, (v,x) => v.CreatedAtUtc=x),
        Time<WorkbenchState>(nameof(WorkbenchState.UpdatedAtUtc), v => v.UpdatedAtUtc, (v,x) => v.UpdatedAtUtc=x),
        Time<WorkbenchState>(nameof(WorkbenchState.SavedAtUtc), v => v.SavedAtUtc, (v,x) => v.SavedAtUtc=x),
        Text<WorkbenchState>(nameof(WorkbenchState.ScopeId), v => v.ScopeId, (v,x) => v.ScopeId=x),
        Text<WorkbenchState>(nameof(WorkbenchState.ScopeName), v => v.ScopeName, (v,x) => v.ScopeName=x),
        Bool<WorkbenchState>(nameof(WorkbenchState.IsCodeViewVisible), v => v.IsCodeViewVisible, (v,x) => v.IsCodeViewVisible=x),
        Bool<WorkbenchState>(nameof(WorkbenchState.IsDiagramViewVisible), v => v.IsDiagramViewVisible, (v,x) => v.IsDiagramViewVisible=x),
        Text<WorkbenchState>(nameof(WorkbenchState.ActiveWorkspaceView), v => v.ActiveWorkspaceView, (v,x) => v.ActiveWorkspaceView=x),
        Text<WorkbenchState>(nameof(WorkbenchState.WorkspaceSplitOrientation), v => v.WorkspaceSplitOrientation, (v,x) => v.WorkspaceSplitOrientation=x),
        Text<WorkbenchState>(nameof(WorkbenchState.CodeViewMode), v => v.CodeViewMode, (v,x) => v.CodeViewMode=x),
        Text<WorkbenchState>(nameof(WorkbenchState.PinnedExplorerDetailTab), v => v.PinnedExplorerDetailTab, (v,x) => v.PinnedExplorerDetailTab=x),
        Bool<WorkbenchState>(nameof(WorkbenchState.ReferenceConnectionLinesEnabled), v => v.ReferenceConnectionLinesEnabled, (v,x) => v.ReferenceConnectionLinesEnabled=x),
        Float<WorkbenchState>(nameof(WorkbenchState.CodeCanvasZoom), v => v.CodeCanvasZoom, (v,x) => v.CodeCanvasZoom=x),
        Float<WorkbenchState>(nameof(WorkbenchState.CodeViewportHorizontalOffset), v => v.CodeViewportHorizontalOffset, (v,x) => v.CodeViewportHorizontalOffset=x),
        Float<WorkbenchState>(nameof(WorkbenchState.CodeViewportVerticalOffset), v => v.CodeViewportVerticalOffset, (v,x) => v.CodeViewportVerticalOffset=x),
        Text<WorkbenchState>(nameof(WorkbenchState.ActiveDocumentPath), v => v.ActiveDocumentPath, (v,x) => v.ActiveDocumentPath=x),
        Text<WorkbenchState>(nameof(WorkbenchState.ActiveDiagramId), v => v.ActiveDiagramId, (v,x) => v.ActiveDiagramId=x),
        Text<WorkbenchState>(nameof(WorkbenchState.ActiveDiagramName), v => v.ActiveDiagramName, (v,x) => v.ActiveDiagramName=x),
        Bool<WorkbenchState>(nameof(WorkbenchState.IsDiagramLocked), v => v.IsDiagramLocked, (v,x) => v.IsDiagramLocked=x),
        Float<WorkbenchState>(nameof(WorkbenchState.DiagramCanvasZoom), v => v.DiagramCanvasZoom, (v,x) => v.DiagramCanvasZoom=x),
        Float<WorkbenchState>(nameof(WorkbenchState.DiagramViewportHorizontalOffset), v => v.DiagramViewportHorizontalOffset, (v,x) => v.DiagramViewportHorizontalOffset=x),
        Float<WorkbenchState>(nameof(WorkbenchState.DiagramViewportVerticalOffset), v => v.DiagramViewportVerticalOffset, (v,x) => v.DiagramViewportVerticalOffset=x));
    public static readonly StateRowMap<ExtensionBackcolorSetting> Extension = new("ExtensionAppearance", "ExtensionAppearanceKey",
        Text<ExtensionBackcolorSetting>(nameof(ExtensionBackcolorSetting.Extension), v => v.Extension, (v,x) => v.Extension=x),
        Text<ExtensionBackcolorSetting>(nameof(ExtensionBackcolorSetting.Backcolor), v => v.Backcolor, (v,x) => v.Backcolor=x),
        Text<ExtensionBackcolorSetting>(nameof(ExtensionBackcolorSetting.Language), v => v.Language, (v,x) => v.Language=x));
    public static readonly StateRowMap<ReferenceHighlightStyleSetting> Style = new("ReferenceStyle", "ReferenceStyleKey",
        Text<ReferenceHighlightStyleSetting>(nameof(ReferenceHighlightStyleSetting.Language), v => v.Language, (v,x) => v.Language=x),
        Enum<ReferenceHighlightStyleSetting, ReferenceEntityKind>(nameof(ReferenceHighlightStyleSetting.Kind), v => v.Kind, (v,x) => v.Kind=x),
        Text<ReferenceHighlightStyleSetting>(nameof(ReferenceHighlightStyleSetting.Foreground), v => v.Foreground, (v,x) => v.Foreground=x),
        Bool<ReferenceHighlightStyleSetting>(nameof(ReferenceHighlightStyleSetting.IsBold), v => v.IsBold, (v,x) => v.IsBold=x),
        Bool<ReferenceHighlightStyleSetting>(nameof(ReferenceHighlightStyleSetting.IsItalic), v => v.IsItalic, (v,x) => v.IsItalic=x),
        Bool<ReferenceHighlightStyleSetting>(nameof(ReferenceHighlightStyleSetting.IsUnderline), v => v.IsUnderline, (v,x) => v.IsUnderline=x));
    public static readonly StateRowMap<DiagramImageDefinition> Image = new("DiagramImageDefinition", "DiagramImageDefinitionKey",
        Text<DiagramImageDefinition>(nameof(DiagramImageDefinition.Id), v => v.Id, (v,x) => v.Id=x),
        Text<DiagramImageDefinition>(nameof(DiagramImageDefinition.Name), v => v.Name, (v,x) => v.Name=x),
        Text<DiagramImageDefinition>(nameof(DiagramImageDefinition.Regex), v => v.Regex, (v,x) => v.Regex=x, true),
        Text<DiagramImageDefinition>(nameof(DiagramImageDefinition.MatchTarget), v => v.MatchTarget, (v,x) => v.MatchTarget=x),
        Text<DiagramImageDefinition>(nameof(DiagramImageDefinition.NameRegex), v => v.NameRegex, (v,x) => v.NameRegex=x, true),
        Text<DiagramImageDefinition>(nameof(DiagramImageDefinition.ContentRegex), v => v.ContentRegex, (v,x) => v.ContentRegex=x, true),
        Text<DiagramImageDefinition>(nameof(DiagramImageDefinition.ResourceTypeFilter), v => v.ResourceTypeFilter, (v,x) => v.ResourceTypeFilter=x),
        Int<DiagramImageDefinition>(nameof(DiagramImageDefinition.SortOrder), v => v.SortOrder, (v,x) => v.SortOrder=x),
        Text<DiagramImageDefinition>(nameof(DiagramImageDefinition.OriginalFileName), v => v.OriginalFileName, (v,x) => v.OriginalFileName=x),
        Text<DiagramImageDefinition>(nameof(DiagramImageDefinition.ImageDataBase64), v => v.ImageDataBase64, (v,x) => v.ImageDataBase64=x, true));
    public static readonly StateRowMap<AppSettings> Settings = new("ApplicationPreference", "ProfileKey",
        Text<AppSettings>("Appearance.Theme", v => v.Appearance.Theme, (v,x) => v.Appearance.Theme=x, column: "Theme"),
        Bool<AppSettings>(nameof(AppSettings.LoadMostRecentWorkbenchOnStartup), v => v.LoadMostRecentWorkbenchOnStartup, (v,x) => v.LoadMostRecentWorkbenchOnStartup=x),
        Bool<AppSettings>("IgnoreWhitespaceByDefault", v => v.ResourceComparison.IgnoreWhitespaceByDefault, (v,x) => v.ResourceComparison.IgnoreWhitespaceByDefault=x),
        Bool<AppSettings>("IgnoreCaseByDefault", v => v.ResourceComparison.IgnoreCaseByDefault, (v,x) => v.ResourceComparison.IgnoreCaseByDefault=x),
        Bool<AppSettings>("EnableInternalLogging", v => v.Diagnostics.EnableInternalLogging, (v,x) => v.Diagnostics.EnableInternalLogging=x),
        Text<AppSettings>("CodeWindows.DefaultBackcolor", v => v.CodeWindows.DefaultBackcolor, (v,x) => v.CodeWindows.DefaultBackcolor=x, column: "DefaultBackcolor"),
        Int<AppSettings>("KeyboardShortcuts.Version", v => v.KeyboardShortcuts.Version, (v,x) => v.KeyboardShortcuts.Version=x, "KeyboardShortcutVersion"),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableCanvasCtrlMousePanning), v => v.KeyboardShortcuts.EnableCanvasCtrlMousePanning, (v,x) => v.KeyboardShortcuts.EnableCanvasCtrlMousePanning=x),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableTabCtrlMouseScrolling), v => v.KeyboardShortcuts.EnableTabCtrlMouseScrolling, (v,x) => v.KeyboardShortcuts.EnableTabCtrlMouseScrolling=x),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableTabCtrlShiftMouseAutoscrolling), v => v.KeyboardShortcuts.EnableTabCtrlShiftMouseAutoscrolling, (v,x) => v.KeyboardShortcuts.EnableTabCtrlShiftMouseAutoscrolling=x),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableCodeShiftMouseAutoscrolling), v => v.KeyboardShortcuts.EnableCodeShiftMouseAutoscrolling, (v,x) => v.KeyboardShortcuts.EnableCodeShiftMouseAutoscrolling=x),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableCodeCtrlShiftMouseScrollbarLockedScrolling), v => v.KeyboardShortcuts.EnableCodeCtrlShiftMouseScrollbarLockedScrolling, (v,x) => v.KeyboardShortcuts.EnableCodeCtrlShiftMouseScrollbarLockedScrolling=x),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableCodeCanvasShiftMousePanning), v => v.KeyboardShortcuts.EnableCodeCanvasShiftMousePanning, (v,x) => v.KeyboardShortcuts.EnableCodeCanvasShiftMousePanning=x),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableCodeCanvasCtrlShiftMouseZooming), v => v.KeyboardShortcuts.EnableCodeCanvasCtrlShiftMouseZooming, (v,x) => v.KeyboardShortcuts.EnableCodeCanvasCtrlShiftMouseZooming=x),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableCodeViewCtrlPlusMinusNavigation), v => v.KeyboardShortcuts.EnableCodeViewCtrlPlusMinusNavigation, (v,x) => v.KeyboardShortcuts.EnableCodeViewCtrlPlusMinusNavigation=x),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableCtrlNumberViewSwitching), v => v.KeyboardShortcuts.EnableCtrlNumberViewSwitching, (v,x) => v.KeyboardShortcuts.EnableCtrlNumberViewSwitching=x),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableCodeTabCtrlASNavigation), v => v.KeyboardShortcuts.EnableCodeTabCtrlASNavigation, (v,x) => v.KeyboardShortcuts.EnableCodeTabCtrlASNavigation=x),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableDiagramCtrlQSidebarToggle), v => v.KeyboardShortcuts.EnableDiagramCtrlQSidebarToggle, (v,x) => v.KeyboardShortcuts.EnableDiagramCtrlQSidebarToggle=x),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableDiagramCtrlWWorkflowSidebar), v => v.KeyboardShortcuts.EnableDiagramCtrlWWorkflowSidebar, (v,x) => v.KeyboardShortcuts.EnableDiagramCtrlWWorkflowSidebar=x),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableDiagramShiftMousePanning), v => v.KeyboardShortcuts.EnableDiagramShiftMousePanning, (v,x) => v.KeyboardShortcuts.EnableDiagramShiftMousePanning=x),
        Bool<AppSettings>(nameof(KeyboardShortcutSettings.EnableDiagramCtrlShiftMouseZooming), v => v.KeyboardShortcuts.EnableDiagramCtrlShiftMouseZooming, (v,x) => v.KeyboardShortcuts.EnableDiagramCtrlShiftMouseZooming=x));
}
